# config file for replaying trajectories

# control settings
v: 500
z: z100
mode: 'states' # can also be poses

# playback settings
subsample: 1

# data settings
data_path: /mnt/hdd/data/yumi_kinesthetics/ #/mnt/hdd/data/yumi_teleop/, /mnt/hdd/data/yumi_flexpendant
cache_path: /mnt/hdd/data/.cache/
save_every: 50

# debug settings
record_torque:
  use: True
